version: "3"

services:
  repository:
    build:
      context: ./repository
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

volumes:
  db:
